### ISSUE TITLE
No suitable driver error/ need help 

### ISSUE THREAD

**Issue by McNees287** [JuliaDatabases/JDBC.jl#24]
I'm trying to connect to a Netezza DB. Here's my code:

```
using JDBC
JavaCall.addClassPath("/path/to/netezza/driver.jar")
JDBC.init()
conn = DriverManager.getConnection("jdbc:netezza://database:port/table/user=user,password=password")
```

returns the following error:

```
LoadError: Error calling Java: java.sql.SQLException: No suitable driver found for jdbc:netezza://database:port/table/user=user,password=password
while loading In[2], in expression starting on line 1
```

Since I've specified the driver above, i'm not sure why I would get this error?

**Comment by aviks** [comment]
I can only suggest double checking that the path and filename of the driver is correct, and the permissions allow reading. Are there any other dependencies for the driver that needs to be added to the classpath? Alternatively, you can try calling the DriverManager.getConnection() method in a small java program, running it with the same classpath, and seeing if that works.

**Comment by McNees287** [comment]
Thanks for the response. 

The driver path is correct. I can connect to the database through R via RJDBC. There are some additional dependencies that are used in the R connection that are not used in the Julia one. I'm not sure how to include these in my Julia connection string, as my Java knowledge is very limited. 

Here's the R Code:
```
library(RJDBC)
.jinit()
.jaddClassPath("path/to/driver.jar")
.jclassPath()

drv <- JDBC(driverClass="org.netezza.Driver", classPath="", identifier.quote="'")
con <- dbConnect(drv, "jdbc:netezza://server:port/db", "user", "password")

```
Which works. How can incorporate this drv statement into the Julia connection?

**Comment by aviks** [comment]
Unfortunately, the netezza drivers don't seem to be freely downloadable, so I cannot check myself how  they are loaded. 

Can you try the following, after the `init()` call, and before the `getConnection` call

```julia
jcall(@jimport(java.lang.Class), "forName", @jimport(java.lang.Class), (JString, ), "org.netezza.Driver")
```

Alternatively, as i said before,  the best way debug this is to create a small Java program that works in your environment.  I am confident this should work, we just need to figure out the idiosyncrasies of netazza and your environment.

**Comment by McNees287** [comment]
Thanks again for the response. 

```
using JavaCall
jcall(@jimport(java.lang.Class), "forName", @jimport(java.lang.Class), (JString, ), "org.netezza.Driver")
```

Throws this:

```
Exception in thread "main" java.lang.ClassNotFoundException: org/netezza/Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
LoadError: Error calling Java: java.lang.ClassNotFoundException: org/netezza/Driver
while loading In[4], in expression starting on line 113
```

**Comment by aviks** [comment]
That error really means that the driver is not in the classpath. I'm assuming that "org.netezza.Driver" is the driver class from your R syntax. You can do a `jar -tvf /path/to/driver.jar` and check the output to see that the class is present in the jar. If it is present, that means the the jar file is not properly registered with the JVM. Ensure that the parameter passed to `JavaCall.addClasspath` is correct, and that this function is called before `init()`.

**Comment by iositan** [comment]
HI

Any resolution on this one?
I'm trying also to get connected to netezza from Julia and had similar problem.

using JDBC
JavaCall.addClassPath("C:\\JDBC\\nzjdbc.jar")
JDBC.init()
using JavaCall
jcall(@jimport(java.lang.Class), "forName", @jimport(java.lang.Class), (JString, ), "org.netezza.Driver")

gives

java.lang.ClassNotFoundException: org/netezza/Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)

**Comment by aviks** [comment]
I can only suggest double checking that the path to the jar is correct, and that the class file is actually present in the jar. This error usually denotes an issue with the class-path. Unfortunately, the driver jar is not freely downloadable, so I cannot verify if there is any particular issue with this jar.

**Comment by iositan** [comment]
Man
The jar location is OK. It has been used in several interfaces already: SPSS, Knime, R, squirrel, AquaDataStudio, Java, etc...!!

The syntax for the addClassPath I did try:
JavaCall.addClassPath("C:/JDBC/nzjdbc.jar")
JavaCall.addClassPath("C:\\JDBC\\nzjdbc.jar")
JavaCall.addClassPath("C:\JDBC\nzjdbc.jar")

none of them is reporting error until try to perform a jcall (load the org.netezza.Driver)

**Comment by iositan** [comment]
JavaCall.addClassPath("C:\\JDBC\\nzjdbc.jar") (double back slash)

**Comment by pnorth423** [comment]
Isn't the issue that the `driverClass` isn't being specified ? If facing the same issue, is there currently a way to specify this ?

**Comment by aviks** [comment]
Generally, for a JDBC 4.0 driver, you do not need to specify the class of the driver, they are loaded automatically (they just need to be in the classpath). For older drivers, the `Class.forName` call will load the driver. According to @McNees287 above, that call failed for him. 

See the code in the tests, for example. https://github.com/JuliaDB/JDBC.jl/blob/963bd8eadafa2cdacfe6bf793529df4c59508163/test/runtests.jl#L14-L17 .  Code like this works for all the drivers I (and others) have tested with. I cannot see what is different with the Netezza drivers. I do not have access to an environment to test this. Even the drivers don't seem to be downloadable. So while I understand this is not ideal, I'm stuck at the moment. 

I've been looking at the rJDBC code. You'll notice that in the normal case, it does not use the driver itself to get the connection. It uses pretty much the same code that we use. https://github.com/s-u/RJDBC/blob/1ed58e146102b85220fe01a48b277e05cd3643ec/R/class.R#L40 . However, in the next line, it has some error handler code that instantiates the driver directly. I don't understand why that case should hold, and so am wary to add non-standard hacks like that without understanding why they should be necessary. 

One thing that might be useful is if someone can write a snippet of Java that connects to netezza successfully. Then we can reverse engineer that to Julia.

**Comment by niczky12** [comment]
I'm running into the same problem. I think the issue is that the driver < 4.0 (whatever that means). And as according to [this site]( https://docs.oracle.com/javase/tutorial/jdbc/basics/connecting.html) You need to manually load this. I'm a Java noob so have no idea how to do that. I think with `RJDBC` this is not an issue as you have the option to set the driver class as pointed out above: 

`JDBC(driverClass="org.netezza.Driver", classPath="", identifier.quote="'")`

@aviks Is there an easy way to do this in Julia? I can send you netezza driver I'm using.

Would love to get rid of R and switch to Julia completely, but I need the netezza connections. :(

**Comment by aviks** [comment]
@niczky12 could you please email me to talk about this in more detail?  avik@sengupta.net

**Comment by aviks** [comment]
OK, I think this will work (you'll need a `JavaCall v0.5.1` at a minimum):

```
using JavaCall
JavaCall.addClassPath("/path/to/netezza-driver.jar")
JDBC.init()
classforname("org.netezza.Driver")
conn = DriverManager.getConnection("jdbc:netezza://database:port/table/user=user,password=password")
```

As to the details of this issue, as mentioned above, the netezza driver is not a `JDBC v4.0` driver, and hence one needs to manually load the class. Unfortunately, the classloader used by default in JNI seems problematic, and a fix was found in https://github.com/JuliaInterop/JavaCall.jl/pull/62 by @dfdx . This now allows us to load the class correctly, something that wasn't working in the comments above.

**Comment by niczky12** [comment]
This works for me just fine. :) Thanks @aviks for the workaround. 👏

**Comment by paandu03** [comment]
Hi,
I am new to java code and need your help here,i am writing java code to connect to Netezza, but i am getting Class not found exception, when using Class.forName(driver).I see your are using Julia but am not clear how to integrate with Java,Could you please put some light over there.
Thanks in Advance!

**Comment by aviks** [comment]
@paandu03 If you are trying this in Java, I don't think we will be able to help here. Please ask you IBM support contacts for help.

**Comment by aviks** [comment]
Fixed [here](https://github.com/JuliaDatabases/JDBC.jl/issues/24#issuecomment-327499260)
