### ISSUE TITLE
Set column types in DataFrames.readtable

### ISSUE THREAD

**Issue by AndreasBahr** [JuliaDatabases/JDBC.jl#28]
Unfortunately the function DataFrames.readtable returns a DataFrame with all columns being type Any. This requires type conversions for building subsets.
e.g.
    df = DataFrames.readtable( ....."select year,dest,sum(import_val) as imp from .....
    df[:year] = map(x -> isna(x) ? NA : convert(Int16, x), df[:year])
    dfy = df[df[:year].==1980, :] # subset for year 1980

I would appreciate a modiefied Funktion which sets column types. I am not Julia expert, so the following  suggestion might be of limited use.

```julia
@require DataFrames begin
using DataFrames
function DataFrames.readtable(rs::JResultSet)
    rsmd = getMetaData(rs)
    cols = getColumnCount(rsmd)
    columns = Array{Any}(cols)
    missings = Array{Any}(cols)
    cnames = Array{Symbol}(cols)
    get_methods = Array{Function}(cols)
    for c in 1:cols
        cty = getColumnType(rsmd,c)
        if cty==JDBC_COLTYPE_SMALLINT
            columns[c] = Array{Int16}(0)
        elseif cty==JDBC_COLTYPE_INTEGER
            columns[c] = Array{Int32}(0)
        elseif cty==JDBC_COLTYPE_BIGINT
            columns[c] = Array{Int64}(0)
        elseif cty==JDBC_COLTYPE_VARCHAR
            columns[c] = Array{String}(0)
        elseif cty in [JDBC_COLTYPE_REAL,JDBC_COLTYPE_FLOAT,JDBC_COLTYPE_DOUBLE,JDBC_COLTYPE_DECIMAL]
            columns[c] = Array{Float64}(0)
        else
            columns[c] = Array{Any}(0)
        end
        missings[c] = Array{Bool}(0)
        cnames[c] = DataFrames.makeidentifier(getColumnName(rsmd, c))
        get_methods[c] = jdbc_get_method(getColumnType(rsmd, c))
    end
    for r in rs
        for c in 1:cols
            push!(columns[c], get_methods[c](rs, c))
            if wasNull(rs)
                push!(missings[c], true)
            else
                push!(missings[c], false)
            end
        end
    end

    dcolumns = Array{Any}(cols)

    for c in 1:cols
        dcolumns[c] = DataArrays.DataArray(columns[c], missings[c])
    end
    return DataFrame(dcolumns, cnames)
end
end #@require
```

**Comment by ExpandingMan** [comment]
A big +1 for this.  This seems absolutely necessary if JDBC is to be of any practical use.  I may make a PR for this

**Comment by aviks** [comment]
Please do. I've been meaning to do this, but other things have unfortunately taken priority. I would be really grateful for a PR.

**Comment by ExpandingMan** [comment]
Working on it right now... by the way, is there any way to know the row count of a query from the metadata?  Would be really nice to allocate the arrays ahead of time rather than pushing onto them.  I'm guessing this is a fundamental limitation.

**Comment by aviks** [comment]
In general, no. The low level database interfaces are usually streaming a cursor. One longer term option is to not do the conversion to DataFrames in this package, but via @quinnj 's DataStream and friends.

**Comment by quinnj** [comment]
That would be an excellent idea; happy to pitch in and do the implementation, unless @ExpandingMan would like to (who is also well-versed in DataStreams).

**Comment by ExpandingMan** [comment]
I'm currently rewriting using DataStreams.  Plan to add a `JDBC.Source` type that wraps `JResultSet`
