### ISSUE TITLE
upcoming deprecation of `Nullable`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaDatabases/JDBC.jl#33]
Instances of `Nullable{T}` should be replaced with `Union{T, Void}` as `Nullable` will become deprecated in 0.7.

I'll make a PR for this at some point but let's get #32 squared away first.

**Comment by aviks** [comment]
As far as I know, Union{T, Void} will be slow in 0.6, so this might need to be version bound to 0.7? Although, having said that, JDBC is not the fastest it could be  right now in any case.

**Comment by ExpandingMan** [comment]
As far as I can tell, `Nullable` is only used to describe the presence of fields in data structures and these only need to be checked as part of initializations and never in loops for pulling data.  Any degradation in performance resulting from a switch to `Union{T, Void}` should therefore be trivial.  (In fact, since the underlying objects are non bits types and they are never used in arrays there may be no performance impact at all.)

**Comment by ExpandingMan** [comment]
This has been done.
