### ISSUE TITLE
deprecation of DBAPI

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaDatabases/JDBC.jl#37]
See [here](https://github.com/JuliaDatabases/DBAPI.jl/issues/16).  I plan to add the parts of DBAPI that are useful to JDBC to this package and remove the dependency on DBAPI in an upcoming PR.

Note that right now this is the only vaguely "Julian" interface to JDBC, so I think it would be very nice to retain a little bit of the basic interface.

**Comment by aviks** [comment]
Yeah, fine by me. thanks.

**Comment by ExpandingMan** [comment]
DBAPI has been completely removed.
