### ISSUE TITLE
JDBC Fails to Load in Julia 1.0 (Nullable not defined)

### ISSUE THREAD

**Issue by PrinceFlorizel** [JuliaDatabases/JDBC.jl#40]
Package installs without any visible issues in Julia 1.0, but when I try to load it (using JDBC), I get the following:

`[ Info: Precompiling JDBC [6042db11-3c3d-5e84-8dba-9cbf74c9ba48]
Loaded /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre/lib/amd64/server/libjvm.so
ERROR: LoadError: UndefVarError: Nullable not defined
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:389
 [7] top-level scope at ./none:3
in expression starting at /home/theuser/.julia/packages/JDBC/epTAb/src/JDBC.jl:6
ERROR: Failed to precompile JDBC [6042db11-3c3d-5e84-8dba-9cbf74c9ba48] to /home/dnovikov/.julia/compiled/v1.0/JDBC/CaptB.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
`

The line in JDBC.jl that Julia is complaining about is
`using Compat: Nullable`

Is there an easy fix to this, or would it be better to wait until a formal update?

**Comment by ExpandingMan** [comment]
I've made a few small fixes for 1.0, including the `using Compat: Nullable` which really just needed to be deleted a while ago.

Unfortunately I'm now running in to a JavaCall error even though JavaCall itself is passing tests on 1.0.

So, we need to fix the JavaCall error and then hopefully this will work.

**Comment by PrinceFlorizel** [comment]
Thank you for the quick fix!  I'm also running into problems with JavaCall now.  Something about being unable to find libjvm.so, even though JAVA_HOME is set to the correct path, and the file is right there in the location where JavaCall is supposedly trying to look.

I'll create a separate post, since JDBC doesn't seem to be the issue anymore.

**Comment by ExpandingMan** [comment]
Yeah, ideally it wouldn't even be necessary to set `JAVA_HOME`, we don't have very good coverage right now for default JVM directories.  We will add some more soon, as well as the remaining fixes to get everything smooth on 1.0.

**Comment by ExpandingMan** [comment]
This is fixed by #41, will close when that's merged.

**Comment by aviks** [comment]
Closed by #41
